# Generated by Django 5.2.8 on 2025-11-27 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Carro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("placa", models.CharField(max_length=10, unique=True)),
                ("marca", models.CharField(max_length=100)),
                ("modelo", models.CharField(max_length=100)),
                ("ano_fabricacao", models.IntegerField()),
                ("em_manutencao", models.BooleanField(default=False)),
                ("data_cadastro", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
