# Generated by Django 5.2.8 on 2025-11-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estoque_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=10, unique=True)),
                ("marca", models.CharField(max_length=10, unique=True)),
                ("valor", models.FloatField()),
                ("quantidade", models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name="Carro",
        ),
    ]
