# Generated by Django 5.2.8 on 2025-12-12 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque_app', '0002_produto_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='marca',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=30),
        ),
    ]
